### ISSUE TITLE
Add non-interactive mode

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/nodejs-portable#27]

**Comment by xiazeyu** [comment]
Is it possible that detect the "node.exe" at startup, when not detected, then start install function.
and also use parameter or add another program to know if the user want to update node.js manually.

Also maybe add this option into the setting file, 
so that the program will like "non-interactive mode", and you won't have to select "2" every time you want to startup.

**Comment by crazy-max** [comment]
It seems possible, I keep your ideas aside ;)
Thanks for your contrib!

**Comment by xiazeyu** [comment]
I tried coding my version in (0f9f46d)
